version: "3.9"

services:
  backend:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: fastapi_app
    ports:
      - "8000:8000"
    volumes:
      - ./app/data:/app/data
    environment:
      - DATABASE_URL=sqlite:///./data/test.db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_API_URL: http://host.docker.internal:8000
    container_name: dfw-frontend
    ports:
      - "3000:80"
    environment:
      - VITE_API_URL=http://backend:8000
    depends_on:
      - backend