version: "3.9"

services:
  backend:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: fastapi_app
    ports:
      - "8000:8000"
    volumes:
      - ./app/test.db:/app/test.db
    environment:
      - DATABASE_URL=sqlite:///./test.db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: dfw-frontend
    ports:
      - "3000:80"
    environment:
      - REACT_APP_API_URL=http://backend:8000
    depends_on:
      - backend